[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
#remappings = [
#    "@iconfoundation/xcall-solidity-library=library/btp2",
#    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts/",
#    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/"
#]